#!/bin/bash
rm -rf *.aux
rm -rf *.lof
rm -rf *.lot
rm -rf *.out
rm -rf *.toc
rm -rf *.bbl
rm -rf *.blg
rm -rf *.brf
rm -rf *.idx
rm -rf *.glo
rm -rf *.ist
rm -rf *.glg
rm -rf *.gls
rm -rf texput.log
